### PR TITLE
Synchronise typed-continuations with upstream/main

### PR DESCRIPTION
**Pull request by dhil**
This PR merges in the latest changes to [bytecodealliance/wasm-tools](https://github.com/bytecodealliance/wasm-tools).

### CODE REVIEW

**Comment by dhil** [comment]
Some regressions have sneaked in during the merge.

**Comment by dhil** [comment]
Commit [9888cf6](https://github.com/effect-handlers/wasm-tools/pull/39/commits/9888cf69a8fb1067bebc99a1363776da08f3080c) fixes a bunch of regressions and implements some functionality for wast parsing / encoding that was previously missing. 

I am trying to get it to parse the `cont.wast` test file. I got most working, I believe, however, there are some remnants of discarded function references proposal instructions in there, I think. I will have a further stab at it later.

**Comment by dhil** [comment]
This is ready now.

**Comment by CosineP** [comment]
Yay!!

**Pull request merged**
